/*
  IMU_Classifier.ino
  ------------------
  Flow:
    1. Wait for a sharp motion (accel sum > threshold).
    2. Capture 119 samples (~1 second).
    3. Feed them into the TFLite interpreter.
    4. Print probabilities to Serial, light the matching LED.

  ----------------------------------------------------------------
  BEFORE COMPILING:
    1. Set BOARD_REV below to match your board (1 or 2).
    2. Drop your `model.h` (downloaded from the Colab) into this folder.
       It should be in the same directory as this .ino file.
    3. Confirm the GESTURES list below matches the order you used in Colab.
  ----------------------------------------------------------------
*/

#define BOARD_REV 2   // 1 = Rev1 (LSM9DS1), 2 = Rev2 (BMI270+BMM150)

#if BOARD_REV == 1
  #include <Arduino_LSM9DS1.h>
#elif BOARD_REV == 2
  #include <Arduino_BMI270_BMM150.h>
#else
  #error "Set BOARD_REV to 1 or 2 at the top of this file."
#endif

#include <Chirale_TensorFlowLite.h>     // main entry point (Chirale fork; replaces the old <TensorFlowLite.h>)
#include <tensorflow/lite/micro/all_ops_resolver.h>
#include <tensorflow/lite/micro/micro_interpreter.h>
#include <tensorflow/lite/schema/schema_generated.h>

#include "model.h"   // generated by the Colab notebook

// -----------------------------------------------------------------
//  Capture parameters — MUST MATCH the Colab notebook
// -----------------------------------------------------------------
const float accelerationThreshold = 2.5;   // g
const int   numSamples            = 119;   // samples per gesture window

// Gesture label order MUST MATCH the GESTURES list in the Colab.
const char* GESTURES[] = { "punch", "flex" };
#define NUM_GESTURES (sizeof(GESTURES) / sizeof(GESTURES[0]))

// -----------------------------------------------------------------
//  TensorFlow Lite Micro globals
// -----------------------------------------------------------------
tflite::AllOpsResolver     tflOpsResolver;

const tflite::Model*       tflModel       = nullptr;
tflite::MicroInterpreter*  tflInterpreter = nullptr;
TfLiteTensor*              tflInputTensor  = nullptr;
TfLiteTensor*              tflOutputTensor = nullptr;

// Working memory for the model. 8 KB is enough for the lab model.
// If you make the model larger, increase this.
constexpr int tensorArenaSize = 8 * 1024;
byte tensorArena[tensorArenaSize] __attribute__((aligned(16)));

int samplesRead = numSamples;

// -----------------------------------------------------------------
void setup() {
  Serial.begin(9600);
  while (!Serial) { ; }

  // ---- IMU ----
  if (!IMU.begin()) {
    Serial.println("IMU.begin() failed. Is BOARD_REV set correctly?");
    while (1) { ; }
  }

  // ---- Model ----
  tflModel = tflite::GetModel(gesture_model_quant_tflite);  // `model` is the byte array in model.h
  if (tflModel->version() != TFLITE_SCHEMA_VERSION) {
    Serial.print("Model schema mismatch. Model is v");
    Serial.print(tflModel->version());
    Serial.print(", library expects v");
    Serial.println(TFLITE_SCHEMA_VERSION);
    while (1) { ; }
  }

  tflInterpreter = new tflite::MicroInterpreter(
      tflModel, tflOpsResolver, tensorArena, tensorArenaSize);

  if (tflInterpreter->AllocateTensors() != kTfLiteOk) {
    Serial.println("AllocateTensors() failed. Try increasing tensorArenaSize.");
    while (1) { ; }
  }

  tflInputTensor  = tflInterpreter->input(0);
  tflOutputTensor = tflInterpreter->output(0);

  // ---- LEDs ----
  pinMode(LEDR, OUTPUT);
  pinMode(LEDG, OUTPUT);
  pinMode(LEDB, OUTPUT);
  digitalWrite(LEDR, HIGH);  // RGB LEDs on the Nano are active-LOW
  digitalWrite(LEDG, HIGH);
  digitalWrite(LEDB, HIGH);

  Serial.println("Ready. Punch or flex the board to classify.");
}

// -----------------------------------------------------------------
void loop() {
  float aX, aY, aZ, gX, gY, gZ;

  // -------- Wait for motion trigger --------
  while (samplesRead == numSamples) {
    if (IMU.accelerationAvailable()) {
      IMU.readAcceleration(aX, aY, aZ);
      float aSum = fabs(aX) + fabs(aY) + fabs(aZ);
      if (aSum >= accelerationThreshold) {
        samplesRead = 0;
        break;
      }
    }
  }

  // -------- Capture one window and feed it to the model --------
  while (samplesRead < numSamples) {
    if (IMU.accelerationAvailable() && IMU.gyroscopeAvailable()) {
      IMU.readAcceleration(aX, aY, aZ);
      IMU.readGyroscope(gX, gY, gZ);

      // *** NORMALIZATION — MUST MATCH THE COLAB EXACTLY ***
      // Accel: assumed range [-4, 4] g  → mapped to [0, 1]
      // Gyro:  assumed range [-2000, 2000] dps → mapped to [0, 1]
      tflInputTensor->data.f[samplesRead * 6 + 0] = (aX + 4.0f)    / 8.0f;
      tflInputTensor->data.f[samplesRead * 6 + 1] = (aY + 4.0f)    / 8.0f;
      tflInputTensor->data.f[samplesRead * 6 + 2] = (aZ + 4.0f)    / 8.0f;
      tflInputTensor->data.f[samplesRead * 6 + 3] = (gX + 2000.0f) / 4000.0f;
      tflInputTensor->data.f[samplesRead * 6 + 4] = (gY + 2000.0f) / 4000.0f;
      tflInputTensor->data.f[samplesRead * 6 + 5] = (gZ + 2000.0f) / 4000.0f;

      samplesRead++;

      if (samplesRead == numSamples) {
        // Run inference
        if (tflInterpreter->Invoke() != kTfLiteOk) {
          Serial.println("Invoke() failed.");
          while (1) { ; }
        }

        // Print all scores, find the argmax
        float maxScore = -1.0f;
        int   maxIdx   = -1;
        for (int i = 0; i < (int)NUM_GESTURES; i++) {
          float score = tflOutputTensor->data.f[i];
          Serial.print(GESTURES[i]);
          Serial.print(": ");
          Serial.println(score, 4);
          if (score > maxScore) { maxScore = score; maxIdx = i; }
        }
        Serial.println();

        // Light up the LED matching the winning gesture
        digitalWrite(LEDR, HIGH);
        digitalWrite(LEDG, HIGH);
        digitalWrite(LEDB, HIGH);
        if      (maxIdx == 0) digitalWrite(LEDR, LOW);  // punch → red
        else if (maxIdx == 1) digitalWrite(LEDG, LOW);  // flex  → green
        // Extend here for more gestures.
      }
    }
  }
}
